"""bookingfile model

Revision ID: 13d80f4e6a05
Revises: cf7d408d3bfe
Create Date: 2024-12-22 05:04:12.035038

"""
from typing import Sequence, Union

from alembic import op
from fastapi_storages import FileSystemStorage
import sqlalchemy as sa


import sqlalchemy_utc
import sqlmodel.sql.sqltypes
import fastapi_storages.integrations.sqlalchemy
from sqlmodel import Text

# revision identifiers, used by Alembic.
revision: str = '13d80f4e6a05'
down_revision: Union[str, None] = 'cf7d408d3bfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('file', fastapi_storages.integrations.sqlalchemy.FileType(storage=FileSystemStorage(path="uploads/bookings")), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name='fk_booking_files_booking_id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booking_files')
    # ### end Alembic commands ###
