"""google_event_id

Revision ID: b41f7909ce01
Revises: 8b8eb7df1606
Create Date: 2025-01-01 15:52:13.232506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


import sqlalchemy_utc
import sqlmodel.sql.sqltypes
from sqlmodel import Text

# revision identifiers, used by Alembic.
revision: str = 'b41f7909ce01'
down_revision: Union[str, None] = '8b8eb7df1606'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('google_event_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'google_event_id')
    # ### end Alembic commands ###
